sudo: required
dist: trusty

language:
    - python
python:
    - "3.6"
addons:
  apt:
    packages:
    - libattr1-dev
    - pkg-config
    - gcc
    - libfuse3-dev
install: test/travis-install.sh
script: test/travis-test.sh
